=== HUPO-PSI/miXML/xml/src/MIF.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v5 U (http://www.xmlspy.com) by Henning Hermjakob (EBI) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="entrySet">
		<xs:annotation>
			<xs:documentation>Root element of the Molecular Interaction Format</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="source" type="nameType" minOccurs="0">
					<xs:annotation>
						<xs:documentation>Describes the source of this entrySet, e.g. the source database.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="entry" type="entryType" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="dbReferenceType">
		<xs:annotation>
			<xs:documentation>Refers to a unique object in an external database.</xs:documentation>
		</xs:annotation>
		<xs:attribute name="db" type="xs:string" use="required"/>
		<xs:attribute name="id" type="xs:string" use="required"/>
		<xs:attribute name="secondary" type="xs:string" use="optional"/>
		<xs:attribute name="version" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="labelType">
		<xs:annotation>
			<xs:documentation>A short alphanumeric label identifying an object. Not necessarily unique.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="fullNameType">
		<xs:annotation>
			<xs:documentation>Full, descriptive object name.</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="nameType">
		<xs:annotation>
			<xs:documentation>Adminstrative data and names.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="shortLabel" type="labelType"/>
			<xs:element name="fullName" type="fullNameType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="bioSourceType">
		<xs:annotation>
			<xs:documentation>Describes the biological source of an object, in simple form only the NCBI taxid.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="names" type="nameType" minOccurs="0"/>
			<xs:element name="tissue" type="fullNameType" minOccurs="0"/>
			<xs:element name="cellType" type="fullNameType" minOccurs="0"/>
			<xs:element name="compartment" type="fullNameType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="featureType">
		<xs:sequence>
			<xs:element name="xref" type="xrefType" minOccurs="0"/>
			<xs:element name="description" type="fullNameType" minOccurs="0"/>
			<xs:element name="location" type="fuzzyLocationType">
				<xs:annotation>
					<xs:documentation>TODO: This is the current EBI location structure derived from EMBL/Genbank. I don't know how similar this is t o the agreed NCBI standard. OK if replaced/updated. </xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="featureIdent" type="methodType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Experimental method used to  identify the feature. If present, this replaces the featureIdent given in the experiment description.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="xrefType">
		<xs:sequence>
			<xs:element name="primaryRef" type="dbReferenceType">
				<xs:annotation>
					<xs:documentation>Primary reference to an external database.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="secondaryRef" type="dbReferenceType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>Further external objects describing the object.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<!--  Feature location definition begins  -->
	<xs:complexType name="positionType">
		<xs:attribute name="position" type="xs:unsignedLong" use="required"/>
	</xs:complexType>
	<xs:complexType name="gapType">
		<xs:complexContent>
			<xs:extension base="positionType">
				<xs:attribute name="length" type="xs:unsignedLong" use="optional"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="intervalType">
		<xs:attribute name="begin" type="xs:unsignedLong" use="required"/>
		<xs:attribute name="end" type="xs:unsignedLong" use="required"/>
	</xs:complexType>
	<xs:complexType name="baseLocationType">
		<xs:annotation>
			<xs:documentation>A location can be either a position, site or have a start and end, only start, only end or is an empty element if the position is unknown.
      The iRef attribute points to an external database reference (equivalent to J00194:100..202 in EMBL).</xs:documentation>
		</xs:annotation>
		<xs:choice>
			<xs:sequence>
				<xs:choice minOccurs="0">
					<xs:element name="begin" type="positionType"/>
					<xs:element name="beginInterval" type="intervalType"/>
				</xs:choice>
				<xs:choice minOccurs="0">
					<xs:element name="end" type="positionType"/>
					<xs:element name="endInterval" type="intervalType"/>
				</xs:choice>
			</xs:sequence>
			<xs:element name="position" type="positionType"/>
			<xs:element name="positionInterval" type="intervalType"/>
			<xs:element name="site" type="positionType"/>
		</xs:choice>
		<xs:attribute name="iRef" type="xs:string" use="optional"/>
		<xs:attribute name="complement" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:complexType name="fuzzyLocationType">
		<xs:annotation>
			<xs:documentation>A location can be either a position, site or have a start and end, only start, only end or is an empty element if the position is unknown.
      The iRef attribute points to an external database reference (equivalent to J00194:100..202 in EMBL).</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="baseLocationType">
				<xs:attribute name="fuzzy" use="optional" default="none">
					<xs:simpleType>
						<xs:restriction base="xs:NMTOKEN">
							<xs:enumeration value="left"/>
							<xs:enumeration value="right"/>
							<xs:enumeration value="both"/>
							<xs:enumeration value="none"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="joinType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="location" type="baseLocationType"/>
				<xs:element name="gap" type="gapType"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute name="fuzzy" use="optional" default="none">
			<xs:simpleType>
				<xs:restriction base="xs:NMTOKEN">
					<xs:enumeration value="left"/>
					<xs:enumeration value="right"/>
					<xs:enumeration value="both"/>
					<xs:enumeration value="none"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="complement" type="xs:boolean" use="optional" default="false"/>
	</xs:complexType>
	<xs:group name="locationGroup">
		<xs:choice>
			<xs:element name="location" type="fuzzyLocationType"/>
			<xs:element name="join" type="joinType"/>
		</xs:choice>
	</xs:group>
	<!--  Feature location definition ends  -->
	<xs:complexType name="interactionType">
		<xs:sequence>
			<xs:annotation>
				<xs:documentation>An interaction has one or more interactors, and thereby covers both binary and n-ary interactions. If specific pairwise interactions are known, they are described by topology  elements.</xs:documentation>
			</xs:annotation>
			<xs:element name="names" type="nameType"/>
			<xs:element name="interactor" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="names" type="nameType"/>
						<xs:element name="xref" type="xrefType" minOccurs="0"/>
						<xs:element name="organism">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="bioSourceType">
										<xs:attribute name="ncbiTaxId" type="xs:integer" use="required"/>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
						<xs:element name="sequence" type="xs:string" minOccurs="0"/>
						<xs:element name="feature" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:complexContent>
									<xs:extension base="featureType">
										<xs:attribute name="id" type="xs:string" use="required"/>
										<xs:attribute name="type" type="xs:string" use="required"/>
									</xs:extension>
								</xs:complexContent>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:attribute name="id" type="xs:string" use="required"/>
					<xs:attribute name="moleculeType" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="AA"/>
								<xs:enumeration value="DNA"/>
								<xs:enumeration value="RNA"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="topology" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="interactorA" type="xs:string" use="required"/>
					<xs:attribute name="interactorB" type="xs:string" use="required"/>
					<xs:attribute name="featureA" type="xs:string" use="optional"/>
					<xs:attribute name="featureB" type="xs:string" use="optional"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="confidence" minOccurs="0">
				<xs:annotation>
					<xs:documentation>TODO: So far the confidence is a single value. We might have multiple values, one or more from each experiment. Should this be modeled?</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:attribute name="unit" type="xs:string" use="required"/>
					<xs:attribute name="value" type="xs:string" use="required"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="entryType">
		<xs:sequence>
			<xs:annotation>
				<xs:documentation>TODO: The semantics of experiment versus interaction  needs to be defined. If more than one experiment is given, are ALL the interactions described by all experiments?</xs:documentation>
			</xs:annotation>
			<xs:element name="interaction" type="interactionType" maxOccurs="unbounded">
				<xs:key name="interactorKey">
					<xs:selector xpath="interactor"/>
					<xs:field xpath="@id"/>
				</xs:key>
				<xs:key name="featureKey">
					<xs:selector xpath="interactor/feature"/>
					<xs:field xpath="@id"/>
				</xs:key>
				<xs:keyref name="interactorAref" refer="interactorKey">
					<xs:selector xpath="topology"/>
					<xs:field xpath="@interactorA"/>
				</xs:keyref>
				<xs:keyref name="interactorBref" refer="interactorKey">
					<xs:selector xpath="topology"/>
					<xs:field xpath="@interactorB"/>
				</xs:keyref>
				<xs:keyref name="featureAref" refer="featureKey">
					<xs:selector xpath="topology"/>
					<xs:field xpath="@featureA"/>
				</xs:keyref>
				<xs:keyref name="featureBref" refer="featureKey">
					<xs:selector xpath="topology"/>
					<xs:field xpath="@featureB"/>
				</xs:keyref>
			</xs:element>
			<xs:element name="experiment" type="experimentType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="methodType">
		<xs:annotation>
			<xs:documentation>Describes an experimental method.</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="names" type="nameType"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
	<xs:complexType name="experimentType">
		<xs:sequence>
			<xs:element name="names" type="nameType"/>
			<xs:element name="xref" type="xrefType">
				<xs:annotation>
					<xs:documentation>Refers to external description  of the experiment, usually by Pubmed IDs.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="organism" minOccurs="0">
				<xs:annotation>
					<xs:documentation>The host organism in which the experiment has been performed.</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="bioSourceType">
							<xs:attribute name="ncbiTaxId" type="xs:integer" use="required"/>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="interactionIdent" type="methodType">
				<xs:annotation>
					<xs:documentation>Experimental method to determine the interaction. Value range externally controlled.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="interactorIdent" type="methodType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Experimental method to determine the interactors involved in the interaction. Value range externally controlled.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="featureIdent" type="methodType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>Experimental method to determine the features of interactors. Value range externally controlled.</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="condition" type="methodType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>TODO: Detailed specification.</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string" use="required"/>
	</xs:complexType>
</xs:schema>

=== HUPO-PSI/miXML/1.0/sampleData/Ito_expand.xml
<?xml version="1.0" encoding="utf-8"?>
<entrySet xmlns="net:sf:psidev:mi" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="net:sf:psidev:mi http://psidev.sourceforge.net/mi/xml/src/MIF.xsd" level="1" version="1">
	
   <entry>
		
      <interactorList>
			
         <proteinInteractor id="YHR119W">
				
            <names>
					
               <shortLabel>YHR119W-SET1</shortLabel>
					
               <fullName>SET domain protein 1</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="Entrez GI" id="529135"/>
					
               <secondaryRef db="RefSeq GI" id="6321911"/>
					
               <secondaryRef db="Entrez Protein_ID" id="AAB68867.1"/>
					
               <secondaryRef db="CandidaDB" id="CA2985"/>
					
               <secondaryRef db="InterPro" id="IPR001214"/>
					
               <secondaryRef db="RefSeq Version" id="NP_011987.1"/>
					
               <secondaryRef db="SwissProt" id="P38827"/>
					
               <secondaryRef db="PIR" id="S48961"/>
					
               <secondaryRef db="GenBank DNA Version" id="U00059.1"/>
					
               <secondaryRef db="MIPS" id="YHR119W"/>
				
            </xref>
			
         </proteinInteractor>
			
         <proteinInteractor id="YEL061C">
				
            <names>
					
               <shortLabel>YEL061C-CIN18</shortLabel>
					
               <fullName>Kinesin-like protein CIN8</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="Entrez GI" id="603257"/>
					
               <secondaryRef db="RefSeq GI" id="6320774"/>
					
               <secondaryRef db="Entrez Protein_ID" id="AAB65026.1"/>
					
               <secondaryRef db="PIR" id="B42641"/>
					
               <secondaryRef db="CandidaDB" id="CA4985"/>
					
               <secondaryRef db="InterPro" id="IPR001752"/>
					
               <secondaryRef db="GenBank DNA Version" id="M90522.1"/>
					
               <secondaryRef db="RefSeq Version" id="NP_010853.1"/>
					
               <secondaryRef db="Swiss-Prot" id="P27895"/>
					
               <secondaryRef db="GenBank DNA Version" id="U18795.1"/>
					
               <secondaryRef db="MIPS" id="YEL061C"/>
					
               <secondaryRef db="GenBank DNA Version" id="Z11859.1"/>
				
            </xref>
			
         </proteinInteractor>
			
         <proteinInteractor id="YCR038C">
				
            <names>
					
               <shortLabel>YCR038C-BUD5</shortLabel>
					
               <fullName>Bud site selection protein BUD5</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="RefSeq GI" id="10383799"/>
					
               <secondaryRef db="Entrez GI" id="1907180"/>
					
               <secondaryRef db="PIR" id="BWBYD5"/>
					
               <secondaryRef db="CandidaDB" id="CA0382"/>
					
               <secondaryRef db="Entrez Protein_ID" id="CAA42305.1"/>
					
               <secondaryRef db="InterPro" id="IPR001895"/>
					
               <secondaryRef db="GenBank DNA Version" id="M63552.1"/>
					
               <secondaryRef db="GenBank DNA Version" id="M68938.1"/>
					
               <secondaryRef db="RefSeq Version" id="NP_009967.2"/>
					
               <secondaryRef db="Swiss-Prot" id="P25300"/>
					
               <secondaryRef db="GenBank DNA Version" id="X56909.1"/>
					
               <secondaryRef db="GenBank DNA Version" id="X59720.2"/>
					
               <secondaryRef db="GenBank DNA Version" id="X63853.1"/>
					
               <secondaryRef db="MIPS" id="YCR038C"/>
				
            </xref>
			
         </proteinInteractor>
			
         <proteinInteractor id="YAL036C">
				
            <names>
					
               <shortLabel>YAL036C-FUN11</shortLabel>
					
               <fullName>Hypothetical 40.7 kDa protein in PYK1-SNC1 intergenic region</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="Entrez GI" id="595548"/>
					
               <secondaryRef db="RefSeq GI" id="6319281"/>
					
               <secondaryRef db="Entrez Protein_ID" id="AAC04995.1"/>
					
               <secondaryRef db="GenBank DNA Version" id="AQ876073.1"/>
					
               <secondaryRef db="CandidaDB" id="CA3893"/>
					
               <secondaryRef db="InterPro" id="IPR000765"/>
					
               <secondaryRef db="RefSeq Version" id="NP_009364.1"/>
					
               <secondaryRef db="Swiss-Prot" id="P39729"/>
					
               <secondaryRef db="PIR" id="S51983"/>
					
               <secondaryRef db="GenBank DNA Version" id="U12980.1"/>
					
               <secondaryRef db="MIPS" id="YAL036C"/>
				
            </xref>
			
         </proteinInteractor>
			
         <proteinInteractor id="YDL065C">
				
            <names>
					
               <shortLabel>YDL065C-PEX19</shortLabel>
					
               <fullName>Farnesylated protein PEX19</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="Entrez GI" id="1431072"/>
					
               <secondaryRef db="RefSeq GI" id="6320138"/>
					
               <secondaryRef db="CandidaDB" id="CA5105"/>
					
               <secondaryRef db="Entrez Protein_ID" id="CAA98630.1"/>
					
               <secondaryRef db="RefSeq Version" id="NP_010218.1"/>
					
               <secondaryRef db="Swiss-Prot" id="Q07418"/>
					
               <secondaryRef db="PIR" id="S67600"/>
					
               <secondaryRef db="MIPS" id="YDL065C"/>
					
               <secondaryRef db="GenBank DNA Version" id="Z74113.1"/>
				
            </xref>
			
         </proteinInteractor>
			
         <proteinInteractor id="YDR532C">
				
            <names>
					
               <shortLabel>YDR532C</shortLabel>
					
               <fullName>Hypothetical protein YDR532C</fullName>
				
            </names>
				
            <xref>
					
               <primaryRef db="RefSeq GI" id="6320741"/>
					
               <secondaryRef db="Entrez GI" id="927799"/>
					
               <secondaryRef db="Entrez Protein_ID" id="AAB64971.1"/>
					
               <secondaryRef db="CandidaDB" id="CA0383"/>
					
               <secondaryRef db="RefSeq Version" id="NP_010821.1"/>
					
               <secondaryRef db="Swiss-Prot" id="Q04431"/>
					
               <secondaryRef db="PIR" id="S69587"/>
					
               <secondaryRef db="GenBank DNA Version" id="U33057.1"/>
					
               <secondaryRef db="MIPS" id="YDR532C"/>
				
            </xref>
			
         </proteinInteractor>
		
      </interactorList>
		
      <experimentList>
			
         <experimentDescription id="exp1">
				
            <names>
					
               <shortLabel>ito</shortLabel>
					
               <fullName>Ito T. two hybrid analysis </fullName>
				
            </names>
				
            <bibref>
					
               <xref>
						
                  <primaryRef db="pubmed" id="10655498"/>
						
                  <secondaryRef db="pubmed" id="11283351"/>
					
               </xref>
				
            </bibref>
				
            <hostOrganism ncbiTaxId="4932"/>
				
            <interactionDetection>
					
               <names>
						
                  <shortLabel>classical two hybrid</shortLabel>
					
               </names>
					
               <xref>
						
                  <primaryRef db="PSI-MI" id="MI:0018"/>
					
               </xref>
				
            </interactionDetection>
				
            <participantDetection>
					
               <names>
						
                  <shortLabel>full identification by sequencing</shortLabel>
					
               </names>
					
               <xref>
						
                  <primaryRef db="PSI-MI" id="MI:0056"/>
					
               </xref>
				
            </participantDetection>
			
         </experimentDescription>
		
      </experimentList>
		
      <interactionList>
			
         <interaction>
				
            <experimentList>
					
               <experimentDescription id="exp1">
				
                  <names>
					
                     <shortLabel>ito</shortLabel>
					
                     <fullName>Ito T. two hybrid analysis </fullName>
				
                  </names>
				
                  <bibref>
					
                     <xref>
						
                        <primaryRef db="pubmed" id="10655498"/>
						
                        <secondaryRef db="pubmed" id="11283351"/>
					
                     </xref>
				
                  </bibref>
				
                  <hostOrganism ncbiTaxId="4932"/>
				
                  <interactionDetection>
					
                     <names>
						
                        <shortLabel>classical two hybrid</shortLabel>
					
                     </names>
					
                     <xref>
						
                        <primaryRef db="PSI-MI" id="MI:0018"/>
					
                     </xref>
				
                  </interactionDetection>
				
                  <participantDetection>
					
                     <names>
						
                        <shortLabel>full identification by sequencing</shortLabel>
					
                     </names>
					
                     <xref>
						
                        <primaryRef db="PSI-MI" id="MI:0056"/>
					
                     </xref>
				
                  </participantDetection>
			
               </experimentDescription>
				
            </experimentList>
				
            <participantList>
					
               <proteinParticipant>
						
                  <proteinInteractor id="YCR038C">
				
                     <names>
					
                        <shortLabel>YCR038C-BUD5</shortLabel>
					
                        <fullName>Bud site selection protein BUD5</fullName>
				
                     </names>
				
                     <xref>
					
                        <primaryRef db="RefSeq GI" id="10383799"/>
					
                        <secondaryRef db="Entrez GI" id="1907180"/>
					
                        <secondaryRef db="PIR" id="BWBYD5"/>
